# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Accessible Reading Technologies"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of Accessible Reading Technologies
baseurl: "/websitewizard" # the subpath of your site, e.g. /blog  
url: "https://Myndex.github.io" # the base hostname & protocol for your site
twitter:
  username: Myndex
author: Myndex
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"
  - "node_modules"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: Myndex/websitewizard-template

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

# remote_theme: w3c/wai-website-theme

collections:
  components:
    area: "Design Components"
    name: "Components"
    shortname: "Components"
    repostitory: Myndex/websitewizard
    output: true
    acknowledgements: false
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - wai-website-plugin
